DATABASE_URI = "mysql+pymysql://root@localhost:3306/wallet_db"

ENV = "dev"
DEBUG = True
SQLALCHEMY_DATABASE_URI = DATABASE_URI
DEBUG_TB_ENABLED = DEBUG
DEBUG_TB_INTERCEPT_REDIRECTS = False
SQLALCHEMY_TRACK_MODIFICATIONS = True
