"""update wallet enabled_at to nullable True

Revision ID: 2ae3b8226203
Revises: 43c98ae7fd76
Create Date: 2024-02-01 08:40:08.502662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "2ae3b8226203"
down_revision = "43c98ae7fd76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wallet", schema=None) as batch_op:
        batch_op.alter_column(
            "enabled_at", existing_type=mysql.DATETIME(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wallet", schema=None) as batch_op:
        batch_op.alter_column(
            "enabled_at", existing_type=mysql.DATETIME(), nullable=False
        )

    # ### end Alembic commands ###
