"""init db migration

Revision ID: 43c98ae7fd76
Revises: 
Create Date: 2024-02-01 08:38:09.679495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "43c98ae7fd76"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallet",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.String(length=100), nullable=False),
        sa.Column("owned_by", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("enabled_at", sa.DateTime(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wallet")
    # ### end Alembic commands ###
