"""empty message

Revision ID: f5598b57d099
Revises: e28851192087
Create Date: 2024-02-01 10:27:37.651036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f5598b57d099"
down_revision = "e28851192087"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("customer_id", sa.String(length=100), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.drop_column("customer_id")

    # ### end Alembic commands ###
